/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.synclab.avro.data;
@org.apache.avro.specific.AvroGenerated
public enum ApplicationType implements org.apache.avro.generic.GenericEnumSymbol<ApplicationType> {
  UNKNOWN, FREE, PAID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ApplicationType\",\"namespace\":\"org.synclab.avro.data\",\"symbols\":[\"UNKNOWN\",\"FREE\",\"PAID\"],\"default\":\"FREE\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
